# Generated by Django 3.1.5 on 2021-01-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aparajitha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=20)),
                ('Addresss', models.CharField(max_length=20)),
                ('Mobilee', models.BigIntegerField()),
                ('Emaill', models.EmailField(max_length=254)),
            ],
        ),
    ]
