# Generated by Django 3.1.5 on 2021-01-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_aparajitha'),
    ]

    operations = [
        migrations.CreateModel(
            name='comfie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfie1', models.CharField(max_length=20)),
                ('comfie2', models.CharField(max_length=20)),
                ('comfie3', models.BigIntegerField()),
                ('comfie4', models.EmailField(max_length=254)),
            ],
        ),
    ]
