# Generated by Django 3.1.5 on 2021-01-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_auto_20210127_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparajitha',
            old_name='Names_name',
            new_name='Names',
        ),
    ]
