# Generated by Django 3.1.5 on 2021-01-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_auto_20210127_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparajitha',
            old_name='Names',
            new_name='Names_name',
        ),
    ]
