# Generated by Django 3.1.5 on 2021-01-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0007_gouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='aparajitha1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicable_at_the_Country_Level', models.CharField(max_length=20)),
                ('Setting_Title', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('Threshold_limit', models.CharField(max_length=20)),
                ('Applicable_Regular_Employee', models.CharField(max_length=20)),
                ('Applicable_Contract_Worker', models.CharField(max_length=20)),
                ('Group_Level', models.CharField(max_length=20)),
                ('Legal_Entity_Level', models.CharField(max_length=20)),
                ('Unit_Level', models.CharField(max_length=20)),
                ('Periodicity', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='aparajitha',
        ),
        migrations.DeleteModel(
            name='comfie',
        ),
        migrations.DeleteModel(
            name='gouse',
        ),
        migrations.DeleteModel(
            name='shaik',
        ),
    ]
