# Generated by Django 3.1.5 on 2021-01-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0008_auto_20210127_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparajitha1',
            old_name='Legal_Entity_Level',
            new_name='Applicable_International_Worker',
        ),
        migrations.RenameField(
            model_name='aparajitha1',
            old_name='Periodicity',
            new_name='Applicable_Trainee',
        ),
        migrations.RemoveField(
            model_name='aparajitha1',
            name='Unit_Level',
        ),
    ]
