# Generated by Django 3.1.5 on 2021-01-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0010_auto_20210127_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparajitha2',
            old_name='Setting_Title',
            new_name='Name',
        ),
    ]
