# Generated by Django 3.1.5 on 2021-01-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0011_auto_20210127_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparajitha2',
            old_name='Name',
            new_name='Setting_Title',
        ),
    ]
