# Generated by Django 3.1.5 on 2021-01-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0012_auto_20210127_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aparajitha2',
            new_name='aparajitha3',
        ),
    ]
