# Generated by Django 3.1.5 on 2021-01-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0013_auto_20210127_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparajitha3',
            old_name='Applicable_Contract_Worker',
            new_name='Contribution_Setting_Id',
        ),
        migrations.RenameField(
            model_name='aparajitha3',
            old_name='Applicable_International_Worker',
            new_name='From_Value',
        ),
        migrations.RenameField(
            model_name='aparajitha3',
            old_name='Applicable_Regular_Employee',
            new_name='Range_ID',
        ),
        migrations.RenameField(
            model_name='aparajitha3',
            old_name='Applicable_Trainee',
            new_name='To_Value',
        ),
        migrations.RemoveField(
            model_name='aparajitha3',
            name='Applicable_at_the_Country_Level',
        ),
        migrations.RemoveField(
            model_name='aparajitha3',
            name='District',
        ),
        migrations.RemoveField(
            model_name='aparajitha3',
            name='Group_Level',
        ),
        migrations.RemoveField(
            model_name='aparajitha3',
            name='Legal_Entity_Level',
        ),
        migrations.RemoveField(
            model_name='aparajitha3',
            name='Setting_Title',
        ),
        migrations.RemoveField(
            model_name='aparajitha3',
            name='State',
        ),
        migrations.RemoveField(
            model_name='aparajitha3',
            name='Threshold_limit',
        ),
    ]
