# Generated by Django 3.1.5 on 2021-01-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0014_auto_20210127_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='aparajitha4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contribution_Setting_Id', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Contribution_Value', models.CharField(max_length=20)),
                ('Emaill', models.EmailField(max_length=254)),
                ('Mode_of_Calculation', models.CharField(max_length=20)),
                ('Payroll_Decution_Applicable', models.CharField(max_length=20)),
            ],
        ),
    ]
