# Generated by Django 3.1.5 on 2021-01-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0015_aparajitha4'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aparajitha4',
            new_name='aparajitha10',
        ),
    ]
