# Generated by Django 3.1.5 on 2021-01-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0016_auto_20210127_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparajitha10',
            name='Contribution_Value',
            field=models.IntegerField(),
        ),
    ]
