# Generated by Django 3.1.5 on 2021-01-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0017_auto_20210127_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparajitha10',
            name='Contribution_Setting_Id',
            field=models.IntegerField(),
        ),
    ]
