# Generated by Django 3.1.5 on 2021-01-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0020_auto_20210127_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='aparajitha6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicable_at_the_Country_Level', models.CharField(max_length=20)),
                ('Setting_Title', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('Threshold_limit', models.CharField(max_length=20)),
            ],
        ),
    ]
