# Generated by Django 3.1.5 on 2021-01-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0023_auto_20210129_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='common_setting1',
            old_name='Contribution_period_starts_on',
            new_name='Name',
        ),
    ]
