# Generated by Django 3.1.5 on 2021-01-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0024_auto_20210129_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='common_setting1',
            old_name='Name',
            new_name='Contribution_period_starts_on',
        ),
    ]
